Feature/auth
Cherry-Squad/fantasy-unicorn-ruby pull request #13
Opened 2021-12-12 18:36 UTC by Vladimir-Konyukhov

Данный PR добавляет поддержку аутентификации с помощью гема Devise_token_auth.
Запросы через /api/v1/auth/
Почитать коротко можно здесь: https://devise-token-auth.gitbook.io/devise-token-auth/
Из изменений, пришлось убрать поле password из User. Вместо него зашифрованный encrypted_password.
При регистрации помимо полей email, password требуется еще username(только из-за того что, оно not null в User, можно убрать эту валидацию или сделать дефолтное значение, потом убрать из контроллера девайса).
Подтверждения по email пока нет, надо настроить почту(я пробовал на тестовом проекте, работает), сделаю в следующий раз.
С тестами соотвественно не все, дополню, как сделаю confirmation.

2021-12-17 08:30 UTC, 6rayWa1cher commented
Я предлагаю, раз уж ты ввел `api/v1`, переместить RegistrationController из `custom/` в `api/v1/auth/`. Так будет проще с роутингом новых контроллеров + все тогда будет в одном месте :)
Объявление RegistrationController тогда будет таким:
```ruby
module Api::V1
  class Auth::RegistrationController < DeviseTokenAuth::RegistrationsController
...
```

2021-12-18 20:13 UTC, 6rayWa1cher requested changes
Хороший первый PR! :+1: Все основные изменения сделаны корректно, devise выдает токены и вроде даже проверяет все.  
Username действительно нужен при регистрации, так что not null действительно оставляем и прибавляем к регистрационной форме.  
По поводу неполноты спеков тебя понял, это не смотрел сейчас.

---

В целом, в основном мои комментарии касаются мелких моментов. Попрошу тебя вычистить код от код-комментов, подредактировать rubocop и несколько поправить спеки.  

---

Есть один момент, который я обнаружил при тестировании. Devise ругается в консоли на объект Rails `session` со всеми параметрами запроса:
```
Started POST "/api/v1/auth/sign_in" for 127.0.0.1 at 2021-12-18 23:11:24 +0300
   (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by DeviseTokenAuth::SessionsController#create as */*
  Parameters: {"email"=>"info@a6raywa1cher.com", "password"=>"[FILTERED]", "session"=>{"email"=>"info@a6raywa1cher.com", "password"=>"[FILTERED]"}}
Unpermitted parameter: :session
...
Completed 200 OK in 272ms (Views: 0.2ms | ActiveRecord: 7.3ms | Allocations: 27521)
```
Чтобы это исправить, сделай пожалуйста так, как описано в этом [комментарии](https://github.com/lynndylanhurley/devise_token_auth/issues/676#issuecomment-303746402) к соответствующему issue.

---

Также, я бы предложил попробовать оформить спеки согласно этой [статье](https://rubyyagi.com/rspec-request-spec/), так как это автоматом все мои комментарии убирает и делает всё красивым и сгруппированным (scenario). Но это уже обсуждаемый момент, если не понравится - можем не применять.

2021-12-18 20:13 UTC, 6rayWa1cher commented on app/models/user.rb
> +  # validates :password, presence: true, length: { in: 4..255 }
Закомментированный код можно убрать

2021-12-18 20:13 UTC, 6rayWa1cher commented on db/migrate/20211212105924_add_tokens_to_users.rb
> +    User.reset_column_information
Для чего делается `reset_column_information` в данном случае? Так просто в гайде написано или что-то произошло?

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/models/user_spec.rb
> +  # end
Этот тест можно убрать тогда полностью

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/models/user_spec.rb
> +  # end
Этот тест можно убрать тогда полностью

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +  # let(:password) { Faker::Internet.password(min_length: 6) }
Закомментированный код можно убрать

2021-12-18 20:13 UTC, 6rayWa1cher commented on app/models/user.rb
> +  # :confirmable
Закомментированный код можно убрать

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      post api_v1_user_session_path(email: '', password: '')
Мне кажется, лучше дать не пустые email и password, а заведомо некорректные. Ибо, как мне кажется, пустые/отсутствующие данные будет отдельным спеком, отличный от `credentials are wrong`.
Например:
```ruby
post api_v1_user_session_path(email: "kek#{email}", password: "ololo#{password}")
```

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +  end
Я предлагаю ввести кейсы в отдельные подконтексты: по сути, у тебя два контекста данных запроса, при этом некоторые спеки связаны между собой.
Например:
```ruby
context 'DELETE api/v1/auth (Destroy user)' do
   context 'With valid data' do
      ...
   end

   context "When auth_headers isn't match with user" do
      ...
   end
end
```

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +  end
Я предлагаю ввести кейсы в отдельные подконтексты: по сути, у тебя два контекста данных запроса, при этом некоторые спеки связаны между собой.  
Также лучше вынести изменяющиеся параметры для двух тестов с помощью let.  
Например:
```ruby
context 'POST api/v1/auth/sign_in (Sign In process)' do
   context 'With valid data' do
      ...
   end

   context "When credentials are wrong" do
      let(:invalid_email) { "kek#{email}" }
      let(:invalid_password) { "ololo#{password}" }
      ...
   end
end
```

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +    end
Возможно, стоит ввести подконтекст `context 'With valid data'`, так как спеки связаны друг с другом

2021-12-18 20:13 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +RSpec.describe 'Authentication', type: :request do # rubocop:disable Metrics/BlockLength
Стоит вынести это игнорирование в `.rubocop.yml`, чтобы не выключать cop каждый раз вручную

2021-12-19 15:22 UTC, 6rayWa1cher commented
Обновлю свой комментарий по поводу scenario. Похоже, лучше сейчас об этом не задумываться, ибо [rswag](https://github.com/rswag/rswag#the-rspec-dsl) будет заставлять писать интеграционные спеки совсем иначе.  
Это не отменяет моих комментариев по поводу контекстов, впрочем :)

2021-12-20 10:01 UTC, Vladimir-Konyukhov commented on db/migrate/20211212105924_add_tokens_to_users.rb
> +    User.reset_column_information
Да, в гайде это было сделано перед тем, как обновить поля другими значениями для существующих записей. Нам это не надо, т.к. база пустая(Не считая твоего seed)

2021-12-20 12:42 UTC, Vladimir-Konyukhov commented
Последние изменения: исправил всё, о чем писал @6rayWa1cher,
Нашел и исправил 500, когда регистрируешься с чужим username,
Добавил спеков.

2021-12-20 15:02 UTC, 6rayWa1cher approved these changes
Отлично, все мои комментарии учтены, как я вижу ^_^ Новые спеки выглядят хорошо.  
Осталось парочка совсем мелких вещей. Я их вынес с suggestions, чтобы их можно было применить одной кнопкой. Предполагая, что ты их прокликаешь, даю свой approve.

2021-12-20 15:02 UTC, 6rayWa1cher commented on app/models/user.rb
> +  validates_uniqueness_of :username
На будущее: лучше не вводить отдельный `validates_*`, а изменить строку 14 на такое:
```ruby
validates :username, presence: true, uniqueness: true, length: { in: 3..25 }
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +      it 'Should respond with error ' do
Лишний пробел :)
```suggestion
      it 'Should respond with error' do
```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +
Желательно проверить, что пользователь также исчез и из базы, по аналогии с `Authentication POST api/v1/auth (Sign Up process) With valid data Should create database record`:
```suggestion

it 'Should remove the database record' do
  expect(User.count).to eq(0)
end

```

2021-12-20 15:02 UTC, 6rayWa1cher commented on spec/requests/authentication_spec.rb
> +    context 'Whith invalid auth_headers' do
Маленькая опечатка
```suggestion
    context 'With invalid auth_headers' do
```

2021-12-25 17:55 UTC, Throder-TVRS approved these changes

2021-12-30 10:30 UTC, G4braG4br approved these changes

2021-12-30 10:35 UTC, merged