Feature/create default cruds for models
Cherry-Squad/fantasy-unicorn-ruby pull request #17
Opened 2022-01-04 12:15 UTC by G4braG4br

В данном PR представлены crud'ы для базовых моделей. А также добавлены тесты на контроллеры (кроме contest_application/contest_application_stock). Возможно код не очень чист, буду рад замечаниям.

2022-01-04 13:21 UTC, 6rayWa1cher requested changes
Неплохая работа! Базовые CRUD'ы на месте ^^  
Пройдемся по некоторым моментам, помимо тех, что обозначены в комментариях:
- Названия private методов различаются от контроллера к контроллеру: где-то есть `for_current_user`, где-то нет, хотя все работают именно с контекстом юзера
- В swagger и в коде возникает путаница: написано `get all briefcases`, `retrieve a briefcase`, однако они работают только с контекстом текущего пользователя. Возможно, стоит обновить названия в swagger и сделать комментарии в коде
- `GET /api/v1/user/` почему-то в swagger'е называется `Get user`, хотя на деле возращает всех пользователей
- Не используются namespace'ы в `routes.rb` (по-хорошему, там вообще должны быть `resources`)
- ContestApplicationController и ContestApplicationStockController существуют, но нет тестов
- Тесты имеют некорректные describe: все почему-то `Auth API`

Добавить в беклог после PR:
- Отсутствует защита от перезаписи некоторых полей и выдача чувствительных полей в UserController
- Отсутствует защита от добавления и изменения Contest'ов (ролевая система)
- Отсутствует защита от изменения Briefcase после его наполнения
- Регистрационное значение цены Stock'а при создании ContestApplicationStock берется с фронта, а не с Finnhub (система очередей запросов к Finnhub) :warning: 
- Не проверяется существование добавляемого Stock'а на стороне Finnhub :warning: 
- Не проверяется наличие добавляемого Achievement'а в whilelist'е
- Не проверяется корректность multiplier при добавлении ContestApplicationStock
- Не хватает получения всех ContestApplicationStock по ContestApplication 
- Заменить `config.change_headers_on_each_request = false` на условие от среды
- Вынести длительность действия портфеля в конфиг

2022-01-04 13:21 UTC, 6rayWa1cher commented on spec/integration/v1/achievement_spec.rb
> +        run_test!
Не проверяется, что achievement'ы были присланы, из-за чего пример response в Swagger выглядит вот так: `[]`

2022-01-04 13:21 UTC, 6rayWa1cher commented on app/controllers/api/v1/briefcase_controller.rb
> +          if stock
Можно объединить в одно условие первого уровня и добавить `elsif`

2022-01-04 13:21 UTC, 6rayWa1cher commented on app/controllers/api/v1/contest_application_controller.rb
> +          user_id: contest_application_create_params[:user_id]
Create не должен выставлять `contest_id`, `final_position`, `fantasy_points_delta` и `coins_delta`. По умолчанию, эти поля должны быть `nil`.

2022-01-04 13:21 UTC, 6rayWa1cher commented on app/controllers/api/v1/contest_application_controller.rb
> +      def update
Этот метод не должен существовать: после регистрации заявка не может измениться

2022-01-04 13:21 UTC, 6rayWa1cher commented on app/controllers/api/v1/contest_application_stock_controller.rb
> +          final_price: contest_application_stock_create_params[:final_price],
Поле final_price не должно приходить с фронта, по умолчанию `nil`

2022-01-04 13:21 UTC, 6rayWa1cher commented on app/controllers/api/v1/contest_application_stock_controller.rb
> +          reg_price: contest_application_stock_create_params[:reg_price],
Поле final_price не должно приходить с фронта, по умолчанию `nil`

2022-01-04 13:21 UTC, 6rayWa1cher commented on app/controllers/api/v1/user_controller.rb
> +      rescue ActiveRecord::RecordNotFound
`find_by` не кидает `ActiveRecord::RecordNotFound`, это делает `find` и `find_by!`: https://stackoverflow.com/a/41337619

2022-01-04 13:21 UTC, 6rayWa1cher commented on spec/integration/v1/stock_spec.rb
> +      security []
Почему так? Это действие тоже должно быть защищено токеном.

2022-01-04 13:21 UTC, 6rayWa1cher commented on spec/integration/v1/stock_spec.rb
> +      security []
Почему так? Это действие тоже должно быть защищено токеном.

2022-01-04 18:10 UTC, 6rayWa1cher reviewed
Промежуточные комментарии добавил

2022-01-04 18:10 UTC, 6rayWa1cher commented on app/controllers/api/v1/briefcase_controller.rb
> +          stock = get_stock
Ходить три раза в базу - плохо :)
```suggestion
        briefcase = get_briefcase_by_id
        stock = get_stock
        if briefcase and stock
```

2022-01-04 18:10 UTC, 6rayWa1cher commented on app/controllers/api/v1/contest_application_stock_controller.rb
>            reg_price: contest_application_stock_create_params[:reg_price],
```suggestion
```

2022-01-04 18:10 UTC, 6rayWa1cher commented on app/controllers/api/v1/contest_application_stock_controller.rb
>                                                              reg_price
```suggestion
```

2022-01-04 18:10 UTC, 6rayWa1cher commented on app/controllers/api/v1/contest_application_stock_controller.rb
>                                                              reg_price
```suggestion
```

2022-01-05 11:36 UTC, Vladimir-Konyukhov approved these changes
Велико

2022-01-06 10:36 UTC, 6rayWa1cher reviewed
Тесты пока не смотрел, только контроллеры. Вроде все выглядят адекватно :) Мне понравилась фильтрация контестов - сделано отлично!

2022-01-06 10:36 UTC, 6rayWa1cher commented on app/controllers/api/v1/briefcases/briefcase_controller.rb
> +              unless briefcase.stock_ids.include? stock.id
```suggestion
              if briefcase.stock_ids.include? stock.id
```

2022-01-06 10:36 UTC, 6rayWa1cher commented on app/controllers/api/v1/contests/contest_controller.rb
> +        # before_action :authenticate_api_v1_user!
```suggestion
        before_action :authenticate_api_v1_user!
```

2022-01-06 10:36 UTC, 6rayWa1cher commented on app/controllers/api/v1/stocks/stock_controller.rb
> +        # before_action :authenticate_api_v1_user!
```suggestion
        before_action :authenticate_api_v1_user!
```

2022-01-06 10:36 UTC, 6rayWa1cher commented on app/controllers/api/v1/users/user_controller.rb
> +          end
По идее, такое невозможно: `before_action :authenticate_api_v1_user!` уже гарантирует, что есть пользователь

2022-01-06 20:25 UTC, 6rayWa1cher approved these changes
Парочка мелких правок и... все готово :) Ура!

2022-01-06 20:25 UTC, 6rayWa1cher commented on spec/integration/v1/briefcase_spec.rb
> +
```suggestion
          begin do
            briefcase.stocks << stock
          end

```

2022-01-06 20:25 UTC, 6rayWa1cher commented on spec/integration/v1/contest_application_spec.rb
> +          parameter name: :contest_id, in: :query, type: :integer, required: false
Лучше вынести этот параметр чуть повыше, в секцию `get`. Мало ли, как rswag на такое среагирует :eyes:

2022-01-06 21:17 UTC, merged